alias: Aerotermia - Offset Dinámico
description: Ajusta el offset (+1/-1) según temp interior, con límites de -5 a 5
triggers:
  - trigger: time_pattern
    hours: "*"
    minutes: "5"
conditions:
  - condition: state
    entity_id: climate.pana_zone_1
    state: heat
  - condition: template
    value_template: "{{ now().hour not in [16, 17, 18, 19] }}"
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {% set ns = namespace(consigna=states('input_number.consigna_temperatura') | float(22.5)) %}
              {% if is_state('input_boolean.modo_vacaciones', 'on') %}
                {% set ns.consigna = ns.consigna - 2 %}
              {% endif %}
              {% if is_state('input_boolean.reduccion_nocturna', 'on') %}
                {% set hd = states('input_datetime.hora_dormir') %}
                {% set dormir = hd if hd not in ['unknown', 'unavailable', 'None'] else '22:00:00' %}
                {% set hdesp = states('input_datetime.hora_despertar') %}
                {% set despertar = hdesp if hdesp not in ['unknown', 'unavailable', 'None'] else '06:00:00' %}
                {% set ahora = now().strftime('%H:%M:%S') %}
                {% if dormir > despertar %}
                  {% if ahora >= dormir or ahora < despertar %}
                    {% set ns.consigna = ns.consigna - 1 %}
                  {% endif %}
                {% else %}
                  {% if ahora >= dormir and ahora < despertar %}
                    {% set ns.consigna = ns.consigna - 1 %}
                  {% endif %}
                {% endif %}
              {% endif %}
              {% set temp_int = states('sensor.promedio_temperatura_int') | float(0) %}
              {{ temp_int > (ns.consigna + 0.4) }}
          - condition: template
            value_template: >-
              {% set temp_ext = states('sensor.promedio_temperatura_ext') | float(0) %}
              {% set actual = state_attr('climate.pana_zone_1', 'temperature') | float(0) %}
              {{ temp_ext < 15 or actual > 0 }}
        sequence:
          - variables:
              target_temp: >-
                {% set actual = state_attr('climate.pana_zone_1', 'temperature') | float(0) %}
                {% set temp_ext = states('sensor.promedio_temperatura_ext') | float(0) %}
                {% set limite_inf = 0 if temp_ext >= 15 else -5 %}
                {{ ([actual - 1, limite_inf] | max) }}
          - repeat:
              sequence:
                - action: climate.set_temperature
                  target:
                    entity_id: climate.pana_zone_1
                  data:
                    temperature: "{{ target_temp }}"
                - delay:
                    minutes: 1
              until:
                - condition: template
                  value_template: >-
                    {{ state_attr('climate.pana_zone_1', 'temperature') | float(0) == target_temp | float(0) or repeat.index >= 5 }}
      - conditions:
          - condition: template
            value_template: >-
              {% set ns = namespace(consigna=states('input_number.consigna_temperatura') | float(22.5)) %}
              {% if is_state('input_boolean.modo_vacaciones', 'on') %}
                {% set ns.consigna = ns.consigna - 2 %}
              {% endif %}
              {% if is_state('input_boolean.reduccion_nocturna', 'on') %}
                {% set hd = states('input_datetime.hora_dormir') %}
                {% set dormir = hd if hd not in ['unknown', 'unavailable', 'None'] else '22:00:00' %}
                {% set hdesp = states('input_datetime.hora_despertar') %}
                {% set despertar = hdesp if hdesp not in ['unknown', 'unavailable', 'None'] else '06:00:00' %}
                {% set ahora = now().strftime('%H:%M:%S') %}
                {% if dormir > despertar %}
                  {% if ahora >= dormir or ahora < despertar %}
                    {% set ns.consigna = ns.consigna - 1 %}
                  {% endif %}
                {% else %}
                  {% if ahora >= dormir and ahora < despertar %}
                    {% set ns.consigna = ns.consigna - 1 %}
                  {% endif %}
                {% endif %}
              {% endif %}
              {% set temp_int = states('sensor.promedio_temperatura_int') | float(0) %}
              {{ temp_int < (ns.consigna - 0.4) }}
        sequence:
          - variables:
              target_temp: >-
                {% set actual = state_attr('climate.pana_zone_1', 'temperature') | float(0) %}
                {{ ([actual + 1, 5] | min) }}
          - repeat:
              sequence:
                - action: climate.set_temperature
                  target:
                    entity_id: climate.pana_zone_1
                  data:
                    temperature: "{{ target_temp }}"
                - delay:
                    minutes: 1
              until:
                - condition: template
                  value_template: >-
                    {{ state_attr('climate.pana_zone_1', 'temperature') | float(0) == target_temp | float(0) or repeat.index >= 5 }}
mode: single
