alias: Optimización Offset Aerotermia Dinámico
description: Ajusta el offset (+1/-1) según temp interior, con límites de -5 a 5
triggers:
  - trigger: time_pattern
    hours: "*"
    minutes: "5"
conditions:
  - condition: state
    entity_id: climate.pana_zone_1
    state: heat
  - condition: template
    value_template: "{{ now().hour not in [16, 17, 18, 19] }}"
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.promedio_temperatura_int
            above: 23
          - condition: numeric_state
            entity_id: sensor.promedio_temperatura_ext
            below: 13
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: climate.pana_zone_1
            data:
              temperature: >
                {% set actual = state_attr('climate.pana_zone_1', 'temperature')
                | float(0) %} {{ ([actual - 1, -5] | max) }}
      - conditions:
          - condition: numeric_state
            entity_id: sensor.promedio_temperatura_int
            below: 22.4
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: climate.pana_zone_1
            data:
              temperature: >
                {% set actual = state_attr('climate.pana_zone_1', 'temperature')
                | float(0) %} {{ ([actual + 1, 5] | min) }}
mode: single
