alias: Aerotermia - Termostato Maestro ON/OFF + Gestión ACS
description: >
  Enciende calefacción cuando la casa está fría (por debajo de la consigna de encendido),
  aplica boost de offset si la temperatura exterior es alta (anti-cycling).
  Al alcanzar la temperatura de apagado, gestiona la carga de ACS si es necesario
  antes de apagar. Todos los umbrales son configurables mediante helpers externos.
mode: single

triggers:
  - hours: /1
    minutes: "1"
    trigger: time_pattern
  - alias: ON < temp_encendido TempInt
    entity_id: sensor.promedio_temperatura_int
    below: input_number.temp_encendido
    trigger: numeric_state
  - alias: OFF > temp_apagado TempInt
    entity_id:
      - sensor.promedio_temperatura_int
    above: input_number.temp_apagado
    trigger: numeric_state
    for:
      hours: 0
      minutes: 15
      seconds: 0

conditions: []

actions:
  - choose:
      # =====================================================
      # RAMA 1: ENCENDIDO — Casa fría, máquina apagada
      # =====================================================
      - conditions:
          - condition: numeric_state
            entity_id: sensor.promedio_temperatura_int
            below: input_number.temp_encendido
          - condition: state
            entity_id: climate.pana_zone_1
            state: "off"
          # --- RESTRICCIÓN HORARIA (OPCIONAL) ---
          # Descomentar el bloque siguiente para evitar arranques en horas punta.
          # Evita encendidos L-V en franjas de alta tarifa eléctrica.
          # - condition: not
          #     conditions:
          #       - condition: time
          #         weekday:
          #           - mon
          #           - tue
          #           - wed
          #           - thu
          #           - fri
          #         after: "10:00:00"
          #         before: "14:00:00"
          #       - condition: time
          #         weekday:
          #           - mon
          #           - tue
          #           - wed
          #           - thu
          #           - fri
          #         after: "18:00:00"
          #         before: "22:00:00"
        sequence:
          - action: climate.set_hvac_mode
            target:
              entity_id: climate.pana_zone_1
            data:
              hvac_mode: heat
          # Anti-cycling: boost +1 si temp exterior alta para garantizar disipación
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: sensor.promedio_temperatura_ext
                    above: input_number.temp_ext_boost
                sequence:
                  - target:
                      entity_id: climate.pana_zone_1
                    data:
                      temperature: 1
                    action: climate.set_temperature
            default:
              - target:
                  entity_id: climate.pana_zone_1
                data:
                  temperature: 0
                action: climate.set_temperature

      # =====================================================
      # RAMA 2: APAGADO — Casa caliente, gestión ACS
      # =====================================================
      - conditions:
          - condition: numeric_state
            entity_id: sensor.promedio_temperatura_int
            above: input_number.temp_apagado
          - condition: state
            entity_id: climate.pana_zone_1
            state: heat
        sequence:
          - delay:
              hours: 0
              minutes: 3
              seconds: 0
              milliseconds: 0
          - choose:
              # --- RAMA ACS: Si el depósito necesita carga (delta >= umbral) ---
              - conditions:
                  - alias: si ACS necesita carga (delta >= umbral)
                    condition: template
                    value_template: >
                      {% set mode = state_attr('water_heater.pana_tank', 'operation_mode') %}
                      {% set current = state_attr('water_heater.pana_tank', 'current_temperature') %}
                      {% set target = state_attr('water_heater.pana_tank', 'temperature') %}
                      {% set delta = states('input_number.delta_acs') | float(5) %}
                      {{ mode in ['off', 'idle'] and current is number and target is number and current <= (target - delta) }}
                  - condition: state
                    entity_id: water_heater.pana_tank
                    attribute: operation_mode
                    state: "off"
                  # --- RESTRICCIÓN HORARIA ACS (OPCIONAL) ---
                  # Descomentar para evitar calentamiento de ACS en horas punta.
                  # Si está activo y se cumplen esas horas, NO se ejecuta el calentado de ACS.
                  # - condition: not
                  #     conditions:
                  #       - condition: time
                  #         weekday:
                  #           - mon
                  #           - tue
                  #           - wed
                  #           - thu
                  #           - fri
                  #         after: "10:00:00"
                  #         before: "14:00:00"
                  #       - condition: time
                  #         weekday:
                  #           - mon
                  #           - tue
                  #           - wed
                  #           - thu
                  #           - fri
                  #         after: "18:00:00"
                  #         before: "22:00:00"
                sequence:
                  - target:
                      entity_id: water_heater.pana_tank
                    data:
                      operation_mode: heating
                    action: water_heater.set_operation_mode
                  - delay:
                      hours: 0
                      minutes: 20
                      seconds: 0
                      milliseconds: 0
                  - action: climate.set_hvac_mode
                    target:
                      entity_id: climate.pana_zone_1
                    data:
                      hvac_mode: "off"
                  - target:
                      entity_id: climate.pana_zone_1
                    data:
                      temperature: 0
                    action: climate.set_temperature
                  - wait_template: >
                      {% set current = state_attr('water_heater.pana_tank','current_temperature') | float(0) %}
                      {% set target = state_attr('water_heater.pana_tank','temperature') | float(0) %}
                      {{ current >= (target - 0.5) }}
                    timeout: "04:00:00"
                    continue_on_timeout: true
                  - wait_for_trigger:
                      - entity_id: water_heater.pana_tank
                        attribute: operation_mode
                        to: idle
                        for:
                          minutes: 15
                        trigger: state
                    timeout:
                      hours: 1
                    continue_on_timeout: true
                  - target:
                      entity_id: water_heater.pana_tank
                    data:
                      operation_mode: "off"
                    action: water_heater.set_operation_mode
                  - data:
                      name: Aerotermia
                      message: >-
                        Calentamiento de ACS finalizado. Modo heating
                        desactivado.
                      entity_id: water_heater.pana_tank
                    action: logbook.log
                alias: IF ACS necesita carga CALENTAR

              # --- RAMA SIN ACS: Si el depósito NO necesita carga, apagar directamente ---
              - conditions:
                  - alias: si ACS NO necesita carga (delta < umbral)
                    condition: template
                    value_template: >
                      {% set mode = state_attr('water_heater.pana_tank', 'operation_mode') %}
                      {% set current = state_attr('water_heater.pana_tank', 'current_temperature') %}
                      {% set target = state_attr('water_heater.pana_tank', 'temperature') %}
                      {% set delta = states('input_number.delta_acs') | float(5) %}
                      {{ mode in ['off', 'idle'] and current is number and target is number and current > (target - delta) }}
                    enabled: true
                sequence:
                  - action: climate.set_hvac_mode
                    target:
                      entity_id: climate.pana_zone_1
                    data:
                      hvac_mode: "off"
                  - target:
                      entity_id: climate.pana_zone_1
                    data:
                      temperature: 0
                    action: climate.set_temperature
                alias: IF ACS NO necesita carga STOP
